name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install Node.js dependencies
        run: npm install

      - name: Update Changelog
        run: |
          mkdir -p content/ja/changelog
          echo "---" > content/ja/changelog/changelog.md
          echo "title: Changelog" >> content/ja/changelog/changelog.md
          echo "date: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> content/ja/changelog/changelog.md
          echo "---" >> content/ja/changelog/changelog.md
          git log --pretty=format:'- %h - %s (%an, %ar)' >> content/ja/changelog/changelog.md

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
